swsnu/swpp18-team5

.gitmodules

wiki 리포가 업데이트 될 때 마다 일일히 pull 해줘서 PR을 날려줘야함
그렇게까지 하면서 굳이 submodule을 유지할 필요가 없기에 그냥 삭제함

Wiki submodule

---

doc/howto/markdown-to-pdf.md

How to make pdf from markdown

---

frontend/src/app/services/party.service.spec.ts
frontend/src/app/services/party.service.ts
frontend/src/app/services/user.service.spec.ts
frontend/src/app/services/user.service.ts

this PR:
* creates a new branch `frontend`
* adds services

add services

---

frontend/src/app/types/party.ts

Add party.ts

---

frontend/src/app/app-routing/app-routing.module.spec.ts
frontend/src/app/app-routing/app-routing.module.ts
frontend/src/app/app.component.html
frontend/src/app/app.component.spec.ts
frontend/src/app/app.module.ts

* implemented app-routing module
* add app-routing module at `app.module.ts`
* add router-outlet at `app.component.html`

add app-routing module

---

frontend/src/app/types/party.ts

* Add PartyPhase Enum
* Add PartyState class

add party state type

---

frontend/src/app/app.component.spec.ts
frontend/src/app/app.module.ts
frontend/src/app/lobby-list-item/lobby-list-item.component.html
frontend/src/app/lobby-list-item/lobby-list-item.component.spec.ts
frontend/src/app/lobby-list-item/lobby-list-item.component.ts

* Generated LobbyListItemComponent 
* Testing with mockLobbyListItem

lobby list item component

---

frontend/src/app/services/user.service.spec.ts
frontend/src/app/services/user.service.ts

This PR:
* adds a frontend user service `services/user.service.ts`
* implements `requestSignIn`
* implements the test code for `requestSignIn`

Frontend user service

---

frontend/src/app/lobby-list-item/lobby-list-item.component.spec.ts

fixed test

---

frontend/src/app/services/party.service.spec.ts
frontend/src/app/services/party.service.ts

* Implemented Party Service
* Testing with mock datas

implemented party service

---

frontend/src/app/app-routing/app-routing.module.ts
frontend/src/app/app.component.html
frontend/src/app/app.module.ts
frontend/src/app/sign-in/sign-in.component.html
frontend/src/app/sign-in/sign-in.component.spec.ts
frontend/src/app/sign-in/sign-in.component.ts

This PR:
* creates frontend sign in component
* creates tests

Frontend signin component

---

frontend/src/app/app-routing/app-routing.module.ts
frontend/src/app/app.module.ts

fix router

---

backend/api/tests.py
backend/api/urls.py
backend/api/views.py

- Return User Information (id, username, email) when successfully logged in
- new `verify_session` endpoint

Backend user auth updated

---

frontend/package.json
frontend/proxy.conf.json
frontend/src/app/app.component.spec.ts
frontend/src/app/app.component.ts
frontend/src/app/app.module.ts
frontend/src/app/services/user.service.ts

This PR:
* adds proxy setting
* adds csrf token setting

Frontend connect django

---

backend/api/models.py
backend/api/tests.py
backend/api/urls.py
backend/api/views.py

Implementing party detail view (`/api/party/:id/`)

party detail view

---

frontend/src/app/app-routing/app-routing.module.ts
frontend/src/app/app.module.ts
frontend/src/app/lobby/lobby.component.html
frontend/src/app/lobby/lobby.component.spec.ts
frontend/src/app/lobby/lobby.component.ts

* Generate LobbyComponent
* Added LobbyComponent at routes
* Check Signed in and Redirection to sign-in
* Get Parties

Implemented LobbyComponent

---

frontend/src/app/app-routing/app-routing.module.ts
frontend/src/app/app.component.html
frontend/src/app/app.module.ts
frontend/src/app/lobby/lobby.component.html
frontend/src/app/lobby/lobby.component.ts
frontend/src/app/party-create/party-create.component.html
frontend/src/app/party-create/party-create.component.spec.ts
frontend/src/app/party-create/party-create.component.ts
frontend/src/app/services/party.service.spec.ts
frontend/src/app/services/party.service.ts

Frontend lobby

---

backend/websocket/consumer.py
backend/websocket/event/__init__.py
backend/websocket/event/error.py
backend/websocket/models.py
backend/websocket/tests.py

Updated Menu Assigning feature to implement original requirements.

Updated Menu Assigning

---

backend/websocket/consumer.py
backend/websocket/event/__init__.py
backend/websocket/tests.py

If the leader is leaving, change the leader to another member and broadcast it to others.

Change leader on leaving

---

etc/caddy/Caddyfile
etc/caddy/caddy.service

Caddyfile and service file

---

etc/caddy/Caddyfile

add `www.moyobob.me` redirection

www redirection

---

backend/backend/settings.py

Set session engine as Redis cache

Session engine setting

---

backend/websocket/consumer.py
backend/websocket/event/__init__.py
backend/websocket/event/error.py
backend/websocket/models.py
backend/websocket/tests/test_phase.py

1. Add `paid_user_id` field to `PartyState` model
1. Add Phase transition commands (e.g. `to.choosing.menu`, `to.ordering`, ...)
1. Add appropriate tests

Phase Transition commands

---

backend/api/views.py

Move `import` statement to the top of the file because of possible performance issue.

Move import statement to top of the file

---

backend/websocket/consumer.py
backend/websocket/exception.py
backend/websocket/tests/test_phase.py

Websocket consumer errors refactoring

---

backend/.dockerignore
backend/.gitignore
backend/README.md
backend/backend/settings.py
backend/docker-compose.yml
backend/requirements.dev.txt
backend/requirements.txt

- Generate secret file
- Debug and Allowed Hosts on environment variable
- Extract environment variable file on docker-compose
- Fixed requirement.txt

More dockerize

---

etc/caddy/Caddyfile

Fixed Caddyfile

---

backend/api/models.py
backend/api/tests.py

- `restaurant` -> `restaurant_id`

Rename json field of Party model

---

.circleci/config.yml
frontend/src/app/lobby/lobby.component.html
frontend/src/app/sign-in/sign-in.component.html
frontend/src/app/sign-up/sign-up.component.html

Debug some error in frontend code, caught by `ng build --prod`

Frontend debug

---

backend/README.md
backend/backend/settings.py

Parse allowed hosts list from environment variable.

Multiple allowed hosts list from envvar

---

etc/caddy/Caddyfile

Fixed proxy

---

frontend/src/app/app.module.ts
frontend/src/app/lobby/lobby.component.ts
frontend/src/app/sign-in/sign-in.component.css
frontend/src/app/sign-in/sign-in.component.html
frontend/src/app/sign-in/sign-in.component.spec.ts
frontend/src/app/sign-in/sign-in.component.ts
frontend/src/styles.css

* Add material modules at app.module.ts
* Modified sign in status
* Add sign in component CSS
* Modified initial `joinedPartyId` to `0` at lobby component
* Add Snack Bar when Wrong Input

Sign In CSS

---

frontend/src/app/sign-in/sign-in.component.css
frontend/src/app/sign-in/sign-in.component.html
frontend/src/app/sign-in/sign-in.component.ts

* Add Sign Up Button at Sign In Component

Add Sign Up Button at Sign In Component

---

backend/test.sh
backend/websocket/consumer.py
backend/websocket/event/__init__.py
backend/websocket/tests/test_restaurant.py

Restaurant events should return user id too

---

backend/api/models.py
backend/api/tests/test_party.py
backend/api/tests/test_record.py
backend/websocket/consumer.py
backend/websocket/tests/__init__.py
backend/websocket/tests/test_menu.py
backend/websocket/tests/test_party.py
backend/websocket/tests/test_phase.py
backend/websocket/tests/test_restaurant.py
backend/websocket/tests/test_util.py

Resolved #94 
- Reduce DB hits
- Change `state` property in Party to `get_state` method to make clear it hit's DB.

Backend DB Optimizing

---

frontend/src/app/app.component.css
frontend/src/app/app.component.html
frontend/src/app/app.component.spec.ts
frontend/src/app/app.component.ts
frontend/src/app/app.module.ts
frontend/src/app/services/user.service.ts
frontend/src/app/sign-in/sign-in.component.css
frontend/src/app/sign-in/sign-in.component.html
frontend/src/app/sign-in/sign-in.component.ts
frontend/src/index.html
frontend/src/styles.css

Frontend Toolbar and Sidebar

---

frontend/src/app/app.component.html
frontend/src/app/app.component.ts

Show signout button when signed in only

---

frontend/src/app/party/party-choosing-menu/party-choosing-menu.component.html
frontend/src/app/party/party-choosing-menu/party-choosing-menu.component.ts
frontend/src/app/party/party.component.html
frontend/src/app/party/party.component.ts
frontend/src/app/services/party.service.ts
frontend/src/app/types/command.ts

Quick alternative fix for #123, only for alpha testing.

to ordering phase button for party leader

---

backend/api/models.py

Append 'id' to the end of fields that actually return id

---

backend/Makefile
backend/api/tests/test_restaurant.py
backend/api/urls.py
backend/api/views.py

Endpoint for listing all restaurants

---

frontend/src/app/party/party-payment/party-payment.component.html
frontend/src/app/party/party-payment/party-payment.component.spec.ts
frontend/src/app/party/party-payment/party-payment.component.ts
frontend/src/app/party/party.component.html
frontend/src/app/party/party.component.spec.ts
frontend/src/app/party/party.component.ts

* 내가 총 얼마를 누구한테(paidUserId까지만 표시) 내야 하는지
* 어떤 메뉴(메뉴명, 메뉴 가격)를 몇 개 시켰는지
* 팟장이라면, party를 종료시키고(partyService의 deleteParty) 본인은 lobby 페이지로 나오도록
구현 했습니다.

Frontend payment

---

frontend/src/app/app.component.html
frontend/src/app/app.component.ts
frontend/src/app/lobby/lobby.component.spec.ts
frontend/src/app/lobby/lobby.component.ts
frontend/src/app/party/party.component.spec.ts
frontend/src/app/party/party.component.ts
frontend/src/app/services/user.service.spec.ts
frontend/src/app/services/user.service.ts
frontend/src/app/sign-in/sign-in.component.spec.ts
frontend/src/app/sign-in/sign-in.component.ts
frontend/src/app/sign-up/sign-up.component.spec.ts
frontend/src/app/sign-up/sign-up.component.ts

Resolves #137 
- Merge `signedUserId` and `SignedUsername` to `user`
- Expose `userUpdate` EventEmitter to follow user state change

Refactored User Service

---

frontend/src/app/auth/auth.guard.ts
frontend/src/app/services/user.service.spec.ts
frontend/src/app/services/user.service.ts

- getUser method
- rename verifyUser to verifySession

getUser method to User Service

---

frontend/src/app/app.component.css
frontend/src/app/party/party.component.css
frontend/src/app/party/party.component.html
frontend/src/app/party/party.component.spec.ts
frontend/src/app/sign-in/sign-in.component.css
frontend/src/app/sign-in/sign-in.component.ts
frontend/src/app/sign-up/sign-up.component.css
frontend/src/app/sign-up/sign-up.component.html
frontend/src/app/sign-up/sign-up.component.spec.ts
frontend/src/app/sign-up/sign-up.component.ts
frontend/src/styles.css

This PR:
* fixes the center issue on main page
* adds CSS for SignUpComponent and PartyComponent
* fixes tests to run

Frontend CSS

---

backend/api/decorator.py
backend/api/tests/test_user.py
backend/api/urls.py
backend/api/views.py

API that returns user detail with given user ID
Resolves #140

API for user detail

---

backend/websocket/consumer.py
backend/websocket/event/error.py
backend/websocket/exception.py
backend/websocket/tests/test_consumer.py
backend/websocket/tests/test_menu.py
backend/websocket/tests/test_phase.py
backend/websocket/util.py

CommandNotAllowedError when command on wrong phase

---

frontend/src/app/party/party-choosing-menu/party-choosing-menu.component.html
frontend/src/app/party/party-choosing-menu/party-choosing-menu.component.spec.ts
frontend/src/app/party/party-choosing-menu/party-choosing-menu.component.ts
frontend/src/app/party/party-choosing-restaurant/party-choosing-restaurant.component.spec.ts
frontend/src/app/party/party-ordering/party-ordering.component.spec.ts
frontend/src/app/party/party-payment/party-payment.component.spec.ts
frontend/src/app/party/party.component.html
frontend/src/app/party/party.component.spec.ts
frontend/src/app/party/party.component.ts
frontend/src/app/services/party.service.ts
frontend/src/app/types/command.ts
frontend/src/app/types/event.ts
frontend/src/app/types/party.ts

This PR:
* shows user to their assigned menus
* shows user how much the assigned menus cost
* shows confirm button to confirm their assignment
* shows other user's confirmation status
* shows the button for transition to Ordering (party leader only)
This PR closes #123.

Issue #123

---

backend/api/models.py
backend/api/views.py
backend/websocket/consumer.py
backend/websocket/tests/test_util.py

delete invalid party and party state

---

frontend/src/app/party/party-choosing-menu/select-menu/select-menu.component.ts

Frontend Fix Price Render Error

---

frontend/src/app/party/party-ordered/party-ordered.component.html
frontend/src/app/party/party-ordered/party-ordered.component.ts
frontend/src/app/party/party-ordering/party-ordering.component.html
frontend/src/app/party/party-ordering/party-ordering.component.ts
frontend/src/app/party/party.component.html
frontend/src/app/party/party.component.spec.ts

This PR:
* shows merged `MenuEntry`s in `Ordering` phase
* shows total cost in `Ordered` phase

Frontend Enhancement

---

frontend/src/app/services/restaurant.service.spec.ts
frontend/src/app/services/restaurant.service.ts
frontend/src/app/services/user.service.spec.ts
frontend/src/app/services/user.service.ts

Caching User, Restaurant, and Menu in each services 
